[package]
name = "ozlrip-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
ozlrip = { path = ".." }

[[bin]]
name = "parse_frame"
path = "fuzz_targets/parse_frame.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_frame"
path = "fuzz_targets/decode_frame.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_limited"
path = "fuzz_targets/decode_limited.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_lz4_node"
path = "fuzz_targets/decode_lz4_node.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_zstd_node"
path = "fuzz_targets/decode_zstd_node.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_concat_node"
path = "fuzz_targets/decode_concat_node.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_splitn_node"
path = "fuzz_targets/decode_splitn_node.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_bitpack_node"
path = "fuzz_targets/decode_bitpack_node.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_constant_node"
path = "fuzz_targets/decode_constant_node.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_conversion_node"
path = "fuzz_targets/decode_conversion_node.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_flatpack_node"
path = "fuzz_targets/decode_flatpack_node.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_transpose_node"
path = "fuzz_targets/decode_transpose_node.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_zigzag_node"
path = "fuzz_targets/decode_zigzag_node.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_delta_node"
path = "fuzz_targets/decode_delta_node.rs"
test = false
doc = false
bench = false
