[package]
name = "ozlrip-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
ozlrip = { path = ".." }

[[bin]]
name = "parse_frame"
path = "fuzz_targets/parse_frame.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_frame"
path = "fuzz_targets/decode_frame.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_limited"
path = "fuzz_targets/decode_limited.rs"
test = false
doc = false
bench = false
