[package]
name = "ozlrip-bench"
version = "0.0.0"
edition = "2024"
publish = false
build = "build.rs"

[workspace]

[features]
default = ["ozlrip/default"]
no-checksum = ["ozlrip/std", "ozlrip/zstd", "ozlrip/lz4"]
paranoid = ["ozlrip/default", "ozlrip/paranoid"]

[dependencies]
ozlrip = { path = "..", default-features = false }

[build-dependencies]
cc = "1.2"

[[bench]]
name = "decode_profiles"
harness = false
