[package]
name = "ozlrip-bench"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[features]
default = ["ozlrip/default"]
no-checksum = ["ozlrip/std", "ozlrip/zstd", "ozlrip/lz4"]

[dependencies]
ozlrip = { path = "..", default-features = false }
rust-openzl = "0.1.0"
rust-openzl-sys = "0.1.0"

[[bench]]
name = "decode_profiles"
harness = false
